name = "cardanoswapplus/escrow"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "'cardanoswapplus/escrow' EscrowDst (payout EVM -> Cardano) and EscrowSrc (source Cardano -> EVM) validators for CardanoSwap+ cross-chain HTLCs"

[repository]
user = "cardanoswapplus"
project = "escrow"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
